### ISSUE TITLE
Incomplete transactions returned by /transaction-info and blocks 106179 and 106180  returned as corrupted by /v1/block API

### ISSUE THREAD

**Issue by starykolarz** [deso-protocol/backend#305]
I just encountered the below transaction output - is it even possible a node processes/returns a transaction without data like transactor, or txn type?

{
   "Error": "",
   "Transactions": [   {
      "TransactionIDBase58Check": "3JuEUX4qCPfGyTKnzVXwCJo21R4nCDaHtGakaNeYpqjYKectiqPs5z",
      "RawTransactionHex": "01ea9eb49e6749e77d93fabfb603f0e2ab5734d8ec2ab3f49cd15025dfdfccd0750001021161b9b84f8b25465b994e17da7cfc1e4396dafc74b232f0605a0b35680a85899711057420ea9eb49e6749e77d93fabfb603f0e2ab5734d8ec2ab3f49cd15025dfdfccd075208251371a91ef86155b1e20eeb194ded13e9f067437cc700313db208cec3b16fe237b22426f6479223a224e65772070726f64756374206166746572204368616e6765227de807d461b0a9ddeaeb8af6ea160121021161b9b84f8b25465b994e17da7cfc1e4396dafc74b232f0605a0b35680a8589041270726f647563744465736372697074696f6e04746573740b70726f647563744e616d650854657374203939390c70726f64756374507269636504323030300b70726f6475637454616773047465737446304402201b9542141a94b95f0643bd0c69defc90c6d42f8e3658ceda8fb22f8b67ae7e0a02207fbdfebd758cddb12c5e1301e873c74a4730965f95e5c74c6a36985639bf7487",
      "Inputs": [      {
         "TransactionIDBase58Check": "3JuEUX6mhtdwbKfhpjVM4kAZ34AFsNFnMhWD8KrbG3KCWrDTz4i34p",
         "Index": 0
      }],
      "Outputs": [      {
         "PublicKeyBase58Check": "BC1YLfoXTvtJGBUnAGifCEstFyr8zAzw567EbBmfcTjGtJWJE8KfpSX",
         "AmountNanos": 2199
      }],
      "SignatureHex": "304402201b9542141a94b95f0643bd0c69defc90c6d42f8e3658ceda8fb22f8b67ae7e0a02207fbdfebd758cddb12c5e1301e873c74a4730965f95e5c74c6a36985639bf7487",
      "TransactionType": "SUBMIT_POST",
      "TransactionMetadata":       {
         "BlockHashHex": "",
         "TxnIndexInBlock": 0,
         "TxnType": "",
         "TransactorPublicKeyBase58Check": "",
         "AffectedPublicKeys": null,
         "TxnOutputs": null
      },
      "ExtraData":       {
         "productDescription": "test",
         "productName": "Test 999",
         "productPrice": "2000",
         "productTags": "test"
      }
   }],
   "LastTransactionIDBase58Check": "",
   "LastPublicKeyTransactionIndex": 0,
   "BalanceNanos": 0
}

**Comment by donhardman** [comment]
```
[
    [
        null,
        {
            "id": "3JuEUX4qCPfGyTKnzVXwCJo21R4nCDaHtGakaNeYpqjYKectiqPs5z",
            "transactor": "BC1YLfoXTvtJGBUnAGifCEstFyr8zAzw567EbBmfcTjGtJWJE8KfpSX",
            "type_id": 5,
            "inputs": [
                [
                    "3JuEUX6mhtdwbKfhpjVM4kAZ34AFsNFnMhWD8KrbG3KCWrDTz4i34p",
                    0
                ]
            ],
            "outputs": [
                [
                    "BC1YLfoXTvtJGBUnAGifCEstFyr8zAzw567EbBmfcTjGtJWJE8KfpSX",
                    2199
                ]
            ],
            "signature": "304402201b9542141a94b95f0643bd0c69defc90c6d42f8e3658ceda8fb22f8b67ae7e0a02207fbdfebd758cddb12c5e1301e873c74a4730965f95e5c74c6a36985639bf7487",
            "meta": {
                "post_hash": "ea9eb49e6749e77d93fabfb603f0e2ab5734d8ec2ab3f49cd15025dfdfccd075",
                "parent_post_hash": "8251371a91ef86155b1e20eeb194ded13e9f067437cc700313db208cec3b16fe",
                "data": {
                    "Body": "New product after Change"
                },
                "reward_points": 1000,
                "stake_points": 12500,
                "timestamp_nanos": "1645459105929188528",
                "is_hidden": true
            },
            "extra": {
                "productDescription": "74657374",
                "productName": "5465737420393939",
                "productPrice": "32303030",
                "productTags": "74657374"
            },
            "size": 374,
            "raw": "01ea9eb49e6749e77d93fabfb603f0e2ab5734d8ec2ab3f49cd15025dfdfccd0750001021161b9b84f8b25465b994e17da7cfc1e4396dafc74b232f0605a0b35680a85899711057420ea9eb49e6749e77d93fabfb603f0e2ab5734d8ec2ab3f49cd15025dfdfccd075208251371a91ef86155b1e20eeb194ded13e9f067437cc700313db208cec3b16fe237b22426f6479223a224e65772070726f64756374206166746572204368616e6765227de807d461b0a9ddeaeb8af6ea160121021161b9b84f8b25465b994e17da7cfc1e4396dafc74b232f0605a0b35680a8589041270726f647563744465736372697074696f6e04746573740b70726f647563744e616d650854657374203939390c70726f64756374507269636504323030300b70726f6475637454616773047465737446304402201b9542141a94b95f0643bd0c69defc90c6d42f8e3658ceda8fb22f8b67ae7e0a02207fbdfebd758cddb12c5e1301e873c74a4730965f95e5c74c6a36985639bf7487"
        }
    ]
]
```

Someone testing products :)

**Comment by starykolarz** [comment]
Exactly; I was just checking this further - blocks 106179 and 106180 seem not fully indexed, on any of the nodes I tried (my own, bitclout.com, node.deso.org, some random from ip list in admin console).

Querying https://bitclout.com/api/v1/block for thosse two blocks shows that transactions don't return associated blockhashhex, or transaction metadata.

Querying transaction-info on IDs contained in blocks - returns 'Could not find transaction.....'

Wonder if it's just an api issue, or something in core?

**Comment by tijno** [comment]
see https://github.com/deso-protocol/backend/pull/306

**Comment by AeonSw4n** [comment]
Thanks for flagging this! We fixed it in https://github.com/deso-protocol/core/pull/222. To fix blocks 106179 and 106180 you need to resync txindex (unfortunately). Our API should be updated tomorrow to reflect this.

There was an inconsistency in how SubmitPost transactions were validated in txindex compared to the blockchain, and it caused txindex to skip blocks.

**Comment by starykolarz** [comment]
Dzięki Piotr!

**Comment by donhardman** [comment]
What about transaction with id 3JuEUX4qCPfGyTKnzVXwCJo21R4nCDaHtGakaNeYpqjYKectiqPs5z that still exists on block and has unexisting post in it but by consensus when transactions are connected it should return error? How is it possible? Can you explain please,  thanks

**Comment by AeonSw4n** [comment]
Yes, this transaction is actually valid. If you parse it, you can notice that it contains both `PostHashToModify` and `ParentStakeID`. Whenever you set `PostHashToModify`, consensus treats this as a post update and skips checking `ParentStakeID` - as it doesn't need to make any updates to the parent post. So in fact, you can put anything in `ParentStakeID` because it doesn't matter. 

What happened is someone submitted a post without a parent and then updated this post with another transaction, which included some arbitrary `ParentStakeID`. Now, consensus is fine with this - because again it doesn't need to do anything to the parent post - but txindex was always checking for the parent regardless of whether you're just updating the post or not. This was an unexpected behavior. 

To give a concrete example, consider someone tagged you in a post, and then someone made a reply to that post. Assuming txindex wouldn't error, and someone modified that reply, you would get a notification from the original post. Such indexing would be incorrect. In reality, what happened was txindex throwing an error and skipping the entire block (because parent didn't exist). We fixed this behavior and also added a check in txindex to correctly index these types of post transactions.
